### ISSUE TITLE
Bitsh init issue

### ISSUE THREAD

**Issue by AlexanderIgnacz** [interplanaria/bitsh#2]
I get this error after running `bitsh` command.
```
/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/insight.js:138
      throw e;
      ^
Invalid Argument
Error
    at new NodeError (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.checkArgument (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)
    at new AddressInfo (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:23:5)
    at Function.AddressInfo.fromInsight (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:33:10)
    at Request._callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/insight.js:133:26)
    at Request.self.callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:1076:12) {
  message: 'Invalid Argument',
  stack: 'Invalid Argument\n' +
    'Error\n' +
    '    at new NodeError (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/errors/index.js:20:41)\n' +
    '    at Object.checkArgument (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)\n' +
    '    at new AddressInfo (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:23:5)\n' +
    '    at Function.AddressInfo.fromInsight (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:33:10)\n' +
    '    at Request._callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/insight.js:133:26)\n' +
    '    at Request.self.callback (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at IncomingMessage.<anonymous> (/Users/oscar/.nvm/versions/node/v13.7.0/lib/node_modules/bitsh/node_modules/request/request.js:1076:12)'
}
```

**Comment by joyote** [comment]
Throwing the same error here:
```  message: 'Invalid Argument',
  stack: 'Invalid Argument\n' +
    'Error\n' +
    '    at new NodeError (/usr/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/errors/index.js:20:41)\n' +
    '    at Object.checkArgument (/usr/lib/node_modules/bitsh/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)\n' +
    '    at new AddressInfo (/usr/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:23:5)\n' +
    '    at Function.AddressInfo.fromInsight (/usr/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/models/addressinfo.js:33:10)\n' +
    '    at Request._callback (/usr/lib/node_modules/bitsh/node_modules/bitcore-explorers/lib/insight.js:133:26)\n' +
    '    at Request.self.callback (/usr/lib/node_modules/bitsh/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:315:20)\n' +
    '    at Request.<anonymous> (/usr/lib/node_modules/bitsh/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (events.js:315:20)\n' +
    '    at IncomingMessage.<anonymous> (/usr/lib/node_modules/bitsh/node_modules/request/request.js:1076:12)'
}
```
Neither `bitsh` or `bitcom` CLIs are working for me unfortunately - `bitsh` throws errors on `init`, though it successfully generates the `.bit` file. However it throws the same error whenever you try to log in to a specified account.

`bitcom` will actually let me try to broadcast a tx, but the network rejects the transaction with a `dust` related error regardless of how well funded the wallet is.

Experienced this on Ubuntu 16.04 and 18.04. Are there any OS-level dependencies that need to be installed?

There's no reason why we can't just broadcast `OP_FALSE OP_RETURN $ useradd [ADDRESS]` elsewhere to make a Bitcom-compatible API scheme until this is fixed, correct?

**Comment by joyote** [comment]
I'm pretty sure `bitcom` fails because it depends on a pre-Genesis version of `datapay` without `OP_FALSE`. Still not sure about `bitsh`. 

EDIT: Oh wow, `bitsh` is also very old and likely dependent on broken versions of `datapay` - no NPM updates in over a year:
https://www.npmjs.com/package/bitsh

**Comment by jLLOSAS** [comment]
Since this isn't working, what's the go to way to make a protocol and write to BitCoin?

**Comment by huwyane** [comment]
![testingBITSH](https://user-images.githubusercontent.com/76540328/104624678-d9c03180-5661-11eb-8bca-637a5ba7184c.png)
